name = "simcpucli"
description = "CLI for CPU simulator"
version = "0.1.0-dev"

authors = ["Brent Seidel"]
maintainers = ["Brent Seidel <brentseidel@mac.com>"]
maintainers-logins = ["BrentSeidel"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/BrentSeidel/Sim-CPU"
tags = ["cpu-simulator"]

executables = ["simcpucli"]

[[depends-on]]
bbs = "~0.1.0"

[[depends-on]]
bbs_lisp = "~0.1.0"
