(setq RA 0)
(setq RPSW 1)
(setq RB 2)
(setq RC 3)
(setq RBC 4)
(setq RD 5)
(setq RE 6)
(setq RDE 7)
(setq RH 8)
(setq RL 9)
(setq RHL 10)
(setq RSP 11)
(setq RPC 12)
(defun watch-sectran ()
  (dowhile (= 1 1)
    (sim-step)
    (if (= (reg-val RPC) #xFB17) ; Start of TRNSEC routine
      (progn (print "TRNSEC: Translating sector ")
             (print (reg-val RBC))
             (terpri)))
    (if (= (reg-val RPC) #xFB1C) ; End of TRNSEC routine
      (progn (print "  TRNSEC: Translated sector ")
             (print (reg-val RHL))
             (terpri)))))

