;
;  This is a collection of functions used in the various test scripts.
;
(defun test-reg (reg-num expected)
  (print "Reg " reg-num " expected " expected " actual " (reg-val reg-num))
  (if (= expected (reg-val reg-num))
    (print " Pass")
    (print " *** FAIL ***"))
  (terpri))
(defun test-mask (expected mask)
  (print "CCR expected " expected ", masked " (and expected mask) ", actual " (and (reg-val 18) mask))
  (if (= (and expected mask) (and (reg-val 18) mask))
    (print " Pass")
    (print " *** FAIL ***"))
  (terpri))
(defun test-meml (address expected)
  (print "Memory " address " expected " expected " actual " (meml address))
  (if (= expected (meml address))
    (print " Pass")
    (print " *** FAIL ***"))
  (terpri))
(defun test-memw (address expected)
  (print "Memory " address " expected " expected " actual " (memw address))
  (if (= expected (memw address))
    (print " Pass")
    (print " *** FAIL ***"))
  (terpri))
